### ISSUE TITLE
ArrayIndexOutOfBounds when creating a simple object.

### ISSUE THREAD

**Issue by MateusAraujoBorges** [zhihan/janala2-gradle#11]
Hello,

Running the following code in janala (Ubuntu 15.04 64-bit, Java 8) results in an exception being thrown.

``` java
package tests.bugreports.putfieldbug;

public class SienaBuggyExample {

  private int irrelevant0;
  private int irrelevant1;
  private Object tmp;


  public SienaBuggyExample() {
    tmp = new Object();
  }

  public static void main(String[] args) {
    SienaBuggyExample tok = new SienaBuggyExample();
    System.out.println("ok");
  }
}
```

Here is the stacktrace:

```
java.lang.ArrayIndexOutOfBoundsException: 2
    at janala.interpreters.ObjectValue.setField(ObjectValue.java:104)
    at janala.interpreters.ConcolicInterpreter.visitPUTFIELD(ConcolicInterpreter.java:1384)
    at janala.logger.inst.PUTFIELD.visit(PUTFIELD.java:16)
    at janala.logger.DirectConcolicExecution.log(DirectConcolicExecution.java:58)
    at janala.logger.AbstractLogger.SPECIAL(AbstractLogger.java:706)
    at janala.logger.DJVM.SPECIAL(DJVM.java:708)
    at tests.bugreports.putfieldbug.SienaBuggyExample.<init>(SienaBuggyExample.java:11)
    at tests.bugreports.putfieldbug.SienaBuggyExample.main(SienaBuggyExample.java:15)
```

After some initial debugging, I believe this issue happens because there is a reference to ObjectValue.NULL instead of the new Object() during the call to SienaBuggyExample' constructor. However, I have no clue why this is happening :(

**Comment by danglotb** [comment]
Hello,

I am experiencing the same issue. (see [this](https://github.com/ksen007/janala2/issues/8))

I am investigating, but **CATG** code is quite complex.

It seems that the returned value by: [this](https://github.com/zhihan/janala2-gradle/blob/master/src/main/java/janala/interpreters/ConcolicInterpreter.java#L1383) is wrong. Maybe one value is missing in the stack.

-- Benjamin.
